[general]
python_version = "3.10"

[browser]
gatherUsageStats = false

[server]
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
